export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

export const MUSICAL_INSTRUMENTS_START = 'MUSICAL_INSTRUMENTS_START';
export const MUSICAL_INSTRUMENTS_GET = 'MUSICAL_INSTRUMENTS_GET';

export const MUSIC_GENRES_START = 'MUSIC_GENRES_START';
export const MUSIC_GENRES_GET = 'MUSIC_GENRES_GET';

export const MUSIC_TEACHERS_START = 'MUSIC_TEACHERS_START';
export const MUSIC_TEACHERS_GET = 'MUSIC_TEACHERS_GET';

export const APPOINTMENTS_START = 'APPOINTMENTS_START';
export const APPOINTMENTS_GET = 'APPOINTMENTS_GET';
export const APPOINTMENTS_CLEAR = 'APPOINTMENTS_CLEAR';
export const APPOINTMENT_CREATE = 'APPOINTMENT_CREATE';
export const APPOINTMENT_SUCCESS = 'APPOINTMENT_SUCCESS';

export const LOADING_FEEDBACK = 'LOADING_FEEDBACK';
export const LOADING_FINISH = 'LOADING_FINISH';
export const MSG_FEEDBACK_SET = 'MSG_FEEDBACK_DISPLAY';
export const MSG_FEEDBACK_FINISH = 'MSG_FEEDBACK_FINISH'
export const APPOINTMENT_FEEDBACK = 'APPOINTMENT_FEEDBACK'
export const APPOINTMENT_FINISH = 'APPOINTMENT_FINISH';