export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const MUSICAL_INSTRUMENTS_START = 'MUSICAL_INSTRUMENTS_START';
export const MUSICAL_INSTRUMENTS_GET = 'MUSICAL_INSTRUMENTS_GET';

export const MUSIC_GENRES_START = 'MUSIC_GENRES_START';
export const MUSIC_GENRES_GET = 'MUSIC_GENRES_GET';